### ISSUE TITLE
Specify what needs to be defined in spec_helper in README.md

### ISSUE THREAD

**Issue by amfarrell** [gocardless/coach#19]
The code example of testing with coach+rspec starts with `require 'spec_helper'`. To help folks who are starting a new project to try out Coach, we should specify what needs to be defined `spec_helper`.

**Comment by nickcampbell18** [comment]
@amfarrell is this still true? I reckon https://github.com/gocardless/coach/blob/master/README.md#testing covers it all now.

**Comment by amfarrell** [comment]
If `spec_helper.rb` is a common thing to define in rails projects, then I suppose so, though when I read that I still worry that there are other things that need to be defined in spec_helper that I'm just unaware of.

**Comment by amfarrell** [comment]
Ah cool. Then this is done.
