### ISSUE TITLE
ActiveSupport::Normalizers instrumentation keys should use reverse domain naming

### ISSUE THREAD

**Issue by wagenet** [gocardless/coach#45]
Instead of `coach.middleware.finish` it should be `finish.middleware.coach` as in Rails itself, e.g `render_template.action_view`.

**Comment by timrogers** [comment]
@wagenet Makes sense! We'll look at making that breaking change in a future version (or you'd be welcome to make a PR yourself, if you'd like).

**Comment by wagenet** [comment]
Fixed in #47.
